### ISSUE TITLE
Error Message when using VGMplug

### ISSUE THREAD

**Issue by shrippen** [HOZHENWAI/Beets-Plugin_VGMdb#17]
Hi, thanks for your fine script!

I started trying it out today and sometimes it works and sometimes I get this error message (which sadly stops beets completely):

VGMplug: Something really wrong happened
Traceback (most recent call last):
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 11 column 10 (char 356)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\arian\AppData\Roaming\beets\Beets-Plugin_VGMdb\beetsplug\VGMplug.py", line 137, in _search_vgmdbinfo
    items = req.json()
            ^^^^^^^^^^
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting property name enclosed in double quotes: line 11 column 10 (char 356)
VGMplug: Network Problem
Traceback (most recent call last):
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 15 column 21 (char 326)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\arian\AppData\Roaming\beets\Beets-Plugin_VGMdb\beetsplug\VGMplug.py", line 346, in album_for_id
    vgmdbinfo = req.json()
                ^^^^^^^^^^
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Unterminated string starting at: line 15 column 21 (char 326)

**Comment by HOZHENWAI** [comment]
hum, can you get the name of the folder for which it bugs? otherwise, I will have to add better logs before proceeding

**Comment by shrippen** [comment]
The name of the folder is 88.9 Pacific Dreams which resides here: F:\Musik\Download\CyberpunkRadio

**Comment by HOZHENWAI** [comment]
New version should fix thoses issues. Unfortunately, I could not reproduce the error you had. So it would be great if you reinstalled the plugin to test.

**Comment by shrippen** [comment]
Hey, thanks for the update. Unfortunately I still get an error message. But it may be a different error as this one is preceded by "Network Exception". I can't remember the other errors containing this:


VGMplug: Network Exception: Never Fade Away
s
Traceback (most recent call last):
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Scripts\beet-script.py", line 33, in <module>
    sys.exit(load_entry_point('beets==1.6.0', 'console_scripts', 'beet')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\site-packages\beets\ui\__init__.py", line 1285, in main
    _raw_main(args)
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\site-packages\beets\ui\__init__.py", line 1272, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\site-packages\beets\ui\commands.py", line 973, in import_func
    import_files(lib, paths, query)
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\site-packages\beets\ui\commands.py", line 943, in import_files
    session.run()
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\site-packages\beets\importer.py", line 340, in run
    pl.run_parallel(QUEUE_SIZE)
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\site-packages\beets\util\pipeline.py", line 446, in run_parallel
    raise exc_info[1].with_traceback(exc_info[2])
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\site-packages\beets\util\pipeline.py", line 311, in run
    out = self.coro.send(msg)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\site-packages\beets\util\pipeline.py", line 193, in coro
    func(*(args + (task,)))
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\site-packages\beets\importer.py", line 1376, in lookup_candidates
    task.lookup_candidates()
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\site-packages\beets\importer.py", line 660, in lookup_candidates
    autotag.tag_album(self.items, search_ids=self.search_ids)
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\site-packages\beets\autotag\match.py", line 461, in tag_album
    for matched_candidate in hooks.album_candidates(items,
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\site-packages\beets\plugins.py", line 573, in decorated
    for v in generator(*args, **kwargs):
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\site-packages\beets\autotag\hooks.py", line 629, in album_candidates
    yield from plugins.candidates(items, artist, album, va_likely,
  File "C:\Users\arian\AppData\Local\Programs\Python\Python311\Lib\site-packages\beets\plugins.py", line 384, in candidates
    yield from plugin.candidates(items, artist, album, va_likely,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arian\AppData\Roaming\beets\Beets-Plugin_VGMdb\beetsplug\VGMplug.py", line 351, in candidates
    albums += self._search_vgmdbinfo(query)
TypeError: 'NoneType' object is not iterable

**Comment by HOZHENWAI** [comment]
ok, it was my bad, should be fixed now

**Comment by shrippen** [comment]
Still getting Network Exceptions


VGMplug: Network Exception: Arion Wind Wilderness Soundtrack
s
Traceback (most recent call last):
  File "C:\Users\arian\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\arian\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\arian\AppData\Local\Programs\Python\Python310\Scripts\beet.exe\__main__.py", line 7, in <module>
  File "C:\Users\arian\AppData\Local\Programs\Python\Python310\lib\site-packages\beets\ui\__init__.py", line 1285, in main
    _raw_main(args)
  File "C:\Users\arian\AppData\Local\Programs\Python\Python310\lib\site-packages\beets\ui\__init__.py", line 1272, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "C:\Users\arian\AppData\Local\Programs\Python\Python310\lib\site-packages\beets\ui\commands.py", line 973, in import_func
    import_files(lib, paths, query)
  File "C:\Users\arian\AppData\Local\Programs\Python\Python310\lib\site-packages\beets\ui\commands.py", line 943, in import_files
    session.run()
  File "C:\Users\arian\AppData\Local\Programs\Python\Python310\lib\site-packages\beets\importer.py", line 340, in run
    pl.run_parallel(QUEUE_SIZE)
  File "C:\Users\arian\AppData\Local\Programs\Python\Python310\lib\site-packages\beets\util\pipeline.py", line 446, in run_parallel
    raise exc_info[1].with_traceback(exc_info[2])
  File "C:\Users\arian\AppData\Local\Programs\Python\Python310\lib\site-packages\beets\util\pipeline.py", line 311, in run
    out = self.coro.send(msg)
  File "C:\Users\arian\AppData\Local\Programs\Python\Python310\lib\site-packages\beets\util\pipeline.py", line 193, in coro
    func(*(args + (task,)))
  File "C:\Users\arian\AppData\Local\Programs\Python\Python310\lib\site-packages\beets\importer.py", line 1376, in lookup_candidates
    task.lookup_candidates()
  File "C:\Users\arian\AppData\Local\Programs\Python\Python310\lib\site-packages\beets\importer.py", line 660, in lookup_candidates
    autotag.tag_album(self.items, search_ids=self.search_ids)
  File "C:\Users\arian\AppData\Local\Programs\Python\Python310\lib\site-packages\beets\autotag\match.py", line 461, in tag_album
    for matched_candidate in hooks.album_candidates(items,
  File "C:\Users\arian\AppData\Local\Programs\Python\Python310\lib\site-packages\beets\plugins.py", line 573, in decorated
    for v in generator(*args, **kwargs):
  File "C:\Users\arian\AppData\Local\Programs\Python\Python310\lib\site-packages\beets\autotag\hooks.py", line 629, in album_candidates
    yield from plugins.candidates(items, artist, album, va_likely,
  File "C:\Users\arian\AppData\Local\Programs\Python\Python310\lib\site-packages\beets\plugins.py", line 384, in candidates
    yield from plugin.candidates(items, artist, album, va_likely,
  File "C:\Users\arian\AppData\Roaming\beets\Beets-Plugin_VGMdb\beetsplug\VGMplug.py", line 351, in candidates
    albums += self._search_vgmdbinfo(query)
TypeError: 'NoneType' object is not iterable

**Comment by shrippen** [comment]
pip show beets-vgmdb shows "WARNING: Package(s) not found: beets-vgmdb".

I have installed the script by downloading the release 1.2.5 and referencing the path as a pluginpath in the beets config.

**Comment by HOZHENWAI** [comment]
can you try:
- delete the release 1.2.5
- do a `pip install beets-vgmdb`
- reference the plugins in the beets config as usual i.e. `plugins: VGMplug`

**Comment by HOZHENWAI** [comment]
in the worst case, i will send you an email, so I can try to mock your folder tree to debug this.

**Comment by shrippen** [comment]
tried it as to your instructions, still giving error messages - please send me a mail I have already uploaded the folder i want to import for you test. mail@arianw.de
